name: peanutprogress
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  provider: ^6.1.2
  flutter_heatmap_calendar: ^1.0.5
  group_button: ^5.3.4
  flutter_colorpicker: ^1.1.0
  cupertino_icons: ^1.0.8
  graphic: ^2.5.0

  d_chart: any
  intl: any
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

lint_staged:
  'lib/**.dart': dart format -l 80 && dart analyze --fatal-infos --fatal-warnings && dart fix --apply