// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRy24rB26rTxB1K5xckrj3xDwsmbzmEG8',
    appId: '1:143894795025:web:79dee835fa7ac546fc32b0',
    messagingSenderId: '143894795025',
    projectId: 'peanut-progress-habit-tracker',
    authDomain: 'peanut-progress-habit-tracker.firebaseapp.com',
    databaseURL: 'https://peanut-progress-habit-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peanut-progress-habit-tracker.firebasestorage.app',
    measurementId: 'G-QEZV893576',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACplrNViHIg737KZ4nduMzC6M08qrgwE',
    appId: '1:143894795025:android:5368f5a01471750dfc32b0',
    messagingSenderId: '143894795025',
    projectId: 'peanut-progress-habit-tracker',
    databaseURL: 'https://peanut-progress-habit-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peanut-progress-habit-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1MdvV-mEfh1jpnXtlkOrY46gmyV-G9pI',
    appId: '1:143894795025:ios:3563bae843033134fc32b0',
    messagingSenderId: '143894795025',
    projectId: 'peanut-progress-habit-tracker',
    databaseURL: 'https://peanut-progress-habit-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peanut-progress-habit-tracker.firebasestorage.app',
    iosBundleId: 'com.example.streaks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1MdvV-mEfh1jpnXtlkOrY46gmyV-G9pI',
    appId: '1:143894795025:ios:3563bae843033134fc32b0',
    messagingSenderId: '143894795025',
    projectId: 'peanut-progress-habit-tracker',
    databaseURL: 'https://peanut-progress-habit-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peanut-progress-habit-tracker.firebasestorage.app',
    iosBundleId: 'com.example.streaks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRy24rB26rTxB1K5xckrj3xDwsmbzmEG8',
    appId: '1:143894795025:web:b635c9df6b76c036fc32b0',
    messagingSenderId: '143894795025',
    projectId: 'peanut-progress-habit-tracker',
    authDomain: 'peanut-progress-habit-tracker.firebaseapp.com',
    databaseURL: 'https://peanut-progress-habit-tracker-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'peanut-progress-habit-tracker.firebasestorage.app',
    measurementId: 'G-ZEFH06G08C',
  );
}
